# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:/Jihoon0146/UKSDT/src/tools/control_dr_reviewer/components/check_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CheckItem(object):
    def setupUi(self, CheckItem):
        CheckItem.setObjectName("CheckItem")
        CheckItem.resize(400, 60)
        CheckItem.setFrameShape(QtWidgets.QFrame.Panel)
        CheckItem.setFrameShadow(QtWidgets.QFrame.Raised)
        CheckItem.setLineWidth(1)
        CheckItem.setMidLineWidth(2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CheckItem.sizePolicy().hasHeightForWidth())
        CheckItem.setSizePolicy(sizePolicy)
        CheckItem.setMinimumSize(QtCore.QSize(0, 60))
        CheckItem.setMaximumSize(QtCore.QSize(16777215, 60))
        self.main_layout = QtWidgets.QHBoxLayout(CheckItem)
        self.main_layout.setContentsMargins(10, 1, 10, 1)
        self.main_layout.setSpacing(10)
        self.main_layout.setObjectName("main_layout")
        self.item_label = QtWidgets.QLabel(CheckItem)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.item_label.setFont(font)
        self.item_label.setObjectName("item_label")
        self.main_layout.addWidget(self.item_label)
        self.radio_layout = QtWidgets.QHBoxLayout()
        self.radio_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.radio_layout.setSpacing(5)
        self.radio_layout.setObjectName("radio_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.radio_layout.addItem(spacerItem)
        self.pass_radio = QtWidgets.QRadioButton(CheckItem)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pass_radio.setFont(font)
        self.pass_radio.setObjectName("pass_radio")
        self.radio_layout.addWidget(self.pass_radio)
        self.fail_radio = QtWidgets.QRadioButton(CheckItem)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fail_radio.setFont(font)
        self.fail_radio.setObjectName("fail_radio")
        self.radio_layout.addWidget(self.fail_radio)
        self.na_radio = QtWidgets.QRadioButton(CheckItem)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.na_radio.setFont(font)
        self.na_radio.setObjectName("na_radio")
        self.radio_layout.addWidget(self.na_radio)
        self.main_layout.addLayout(self.radio_layout)
        self.comment_text = QtWidgets.QTextEdit(CheckItem)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comment_text.setFont(font)
        self.comment_text.setMinimumSize(QtCore.QSize(0, 40))
        self.comment_text.setMaximumSize(QtCore.QSize(16777215, 40))
        self.comment_text.setObjectName("comment_text")
        self.main_layout.addWidget(self.comment_text)
        self.main_layout.setStretch(0, 2)
        self.main_layout.setStretch(1, 2)
        self.main_layout.setStretch(2, 3)

        self.retranslateUi(CheckItem)
        QtCore.QMetaObject.connectSlotsByName(CheckItem)

    def retranslateUi(self, CheckItem):
        _translate = QtCore.QCoreApplication.translate
        CheckItem.setStyleSheet(_translate("CheckItem", "QFrame#CheckItem { background-color: rgb(100, 100, 100); }"))
        CheckItem.setWindowTitle(_translate("CheckItem", "Check Item"))
        self.item_label.setText(_translate("CheckItem", "체크 항목"))
        self.pass_radio.setText(_translate("CheckItem", "Pass"))
        self.fail_radio.setText(_translate("CheckItem", "Fail"))
        self.na_radio.setText(_translate("CheckItem", "N/A"))
        self.comment_text.setPlaceholderText(_translate("CheckItem", "비고사항을 입력하세요..."))
