# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:/Jihoon0146/UKSDT/src/core/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1200)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 800))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.main_layout.setContentsMargins(10, 0, 0, 0)
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName("main_layout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setStyleSheet("")
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.sidebar_placeholder = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidebar_placeholder.sizePolicy().hasHeightForWidth())
        self.sidebar_placeholder.setSizePolicy(sizePolicy)
        self.sidebar_placeholder.setMinimumSize(QtCore.QSize(252, 0))
        self.sidebar_placeholder.setMaximumSize(QtCore.QSize(252, 16777215))
        self.sidebar_placeholder.setStyleSheet("")
        self.sidebar_placeholder.setObjectName("sidebar_placeholder")
        self.content_area = QtWidgets.QWidget(self.splitter)
        self.content_area.setStyleSheet("")
        self.content_area.setObjectName("content_area")
        self.content_layout = QtWidgets.QVBoxLayout(self.content_area)
        self.content_layout.setContentsMargins(20, 20, 20, 20)
        self.content_layout.setSpacing(20)
        self.content_layout.setObjectName("content_layout")
        self.tool_tabs = QtWidgets.QTabWidget(self.content_area)
        self.tool_tabs.setStyleSheet("")
        self.tool_tabs.setTabsClosable(True)
        self.tool_tabs.setMovable(True)
        self.tool_tabs.setObjectName("tool_tabs")
        self.content_layout.addWidget(self.tool_tabs)
        self.main_layout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UKSDT 통합 툴"))
