# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:/Jihoon0146/UKSDT/src/tools/projects/components/prj_child.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChildrenView(object):
    def setupUi(self, ChildrenView):
        ChildrenView.setObjectName("ChildrenView")
        self.verticalLayout = QtWidgets.QVBoxLayout(ChildrenView)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableChildren = QtWidgets.QTableWidget(ChildrenView)
        self.tableChildren.setObjectName("tableChildren")
        self.tableChildren.setColumnCount(3)
        self.tableChildren.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableChildren.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableChildren.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableChildren.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.tableChildren)

        self.retranslateUi(ChildrenView)
        QtCore.QMetaObject.connectSlotsByName(ChildrenView)

    def retranslateUi(self, ChildrenView):
        _translate = QtCore.QCoreApplication.translate
        item = self.tableChildren.horizontalHeaderItem(0)
        item.setText(_translate("ChildrenView", "ID"))
        item = self.tableChildren.horizontalHeaderItem(1)
        item.setText(_translate("ChildrenView", "이름"))
        item = self.tableChildren.horizontalHeaderItem(2)
        item.setText(_translate("ChildrenView", "상태"))
