# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Dev/UKSDT/UKSDT/src/tools/projects/components/prj_detailview.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProjectsDetailView(object):
    def setupUi(self, ProjectsDetailView):
        ProjectsDetailView.setObjectName("ProjectsDetailView")
        self.verticalLayout = QtWidgets.QVBoxLayout(ProjectsDetailView)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackRight = QtWidgets.QStackedWidget(ProjectsDetailView)
        self.stackRight.setObjectName("stackRight")
        self.pageChildren = QtWidgets.QWidget()
        self.pageChildren.setObjectName("pageChildren")
        self.stackRight.addWidget(self.pageChildren)
        self.pageProjectDetail = QtWidgets.QWidget()
        self.pageProjectDetail.setObjectName("pageProjectDetail")
        self.stackRight.addWidget(self.pageProjectDetail)
        self.pageWrapperDetail = QtWidgets.QWidget()
        self.pageWrapperDetail.setObjectName("pageWrapperDetail")
        self.stackRight.addWidget(self.pageWrapperDetail)
        self.verticalLayout.addWidget(self.stackRight)

        self.retranslateUi(ProjectsDetailView)
        QtCore.QMetaObject.connectSlotsByName(ProjectsDetailView)

    def retranslateUi(self, ProjectsDetailView):
        pass
