# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:/Jihoon0146/UKSDT/src/core/components/welcome_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WelcomePage(object):
    def setupUi(self, WelcomePage):
        WelcomePage.setObjectName("WelcomePage")
        WelcomePage.resize(800, 600)
        self.main_layout = QtWidgets.QVBoxLayout(WelcomePage)
        self.main_layout.setContentsMargins(50, 50, 50, 50)
        self.main_layout.setSpacing(40)
        self.main_layout.setObjectName("main_layout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.main_layout.addItem(spacerItem)
        self.welcome_title = QtWidgets.QLabel(WelcomePage)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.welcome_title.setFont(font)
        self.welcome_title.setStyleSheet("color: #2c3e50; margin-bottom: 20px;")
        self.welcome_title.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome_title.setObjectName("welcome_title")
        self.main_layout.addWidget(self.welcome_title)
        self.welcome_subtitle = QtWidgets.QLabel(WelcomePage)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.welcome_subtitle.setFont(font)
        self.welcome_subtitle.setStyleSheet("color: #7f8c8d; margin-bottom: 40px;")
        self.welcome_subtitle.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome_subtitle.setObjectName("welcome_subtitle")
        self.main_layout.addWidget(self.welcome_subtitle)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.main_layout.addItem(spacerItem1)

        self.retranslateUi(WelcomePage)
        QtCore.QMetaObject.connectSlotsByName(WelcomePage)

    def retranslateUi(self, WelcomePage):
        _translate = QtCore.QCoreApplication.translate
        WelcomePage.setWindowTitle(_translate("WelcomePage", "Welcome"))
        self.welcome_title.setText(_translate("WelcomePage", "UKSDT 통합 툴에 오신 것을 환영합니다!"))
        self.welcome_subtitle.setText(_translate("WelcomePage", "왼쪽 사이드바에서 원하는 도구를 선택하여 시작하세요."))
