# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:/Jihoon0146/UKSDT/src/tools/projects/projects.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Projects(object):
    def setupUi(self, Projects):
        Projects.setObjectName("Projects")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Projects.sizePolicy().hasHeightForWidth())
        Projects.setSizePolicy(sizePolicy)
        Projects.setStyleSheet("")
        self.main_layout = QtWidgets.QHBoxLayout(Projects)
        self.main_layout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.main_layout.setContentsMargins(5, 5, 5, 5)
        self.main_layout.setSpacing(10)
        self.main_layout.setObjectName("main_layout")
        self.splitter = QtWidgets.QSplitter(Projects)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.leftPane = QtWidgets.QFrame(self.splitter)
        self.leftPane.setMinimumWidth(220)
        self.leftPane.setMaximumWidth(300)
        self.leftPane.setObjectName("leftPane")
        self.leftLayout = QtWidgets.QVBoxLayout(self.leftPane)
        self.leftLayout.setObjectName("leftLayout")
        self.rightPane = QtWidgets.QFrame(self.splitter)
        self.rightPane.setObjectName("rightPane")
        self.rightLayout = QtWidgets.QVBoxLayout(self.rightPane)
        self.rightLayout.setObjectName("rightLayout")
        self.main_layout.addWidget(self.splitter)

        self.retranslateUi(Projects)
        QtCore.QMetaObject.connectSlotsByName(Projects)

    def retranslateUi(self, Projects):
        _translate = QtCore.QCoreApplication.translate
        Projects.setWindowTitle(_translate("Projects", "Projects"))
